### ISSUE TITLE
Can't log in with localhost

### ISSUE THREAD

**Issue by arthurgustin** [acoshift/session#66]
Hi, I'm doing applicative maintenance on leaptips, I can't login on windows at home. I get the followign stacktrace: 

```
2018/04/06 22:56:02 http: panic serving [::1]:7671: session: dial tcp [::1]:6379: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
goroutine 238 [running]:
net/http.(*conn).serve.func1(0xc0423ed040)
	C:/Go/src/net/http/server.go:1697 +0xd7
panic(0x91be40, 0xc042031a70)
	C:/Go/src/runtime/panic.go:491 +0x291
github.com/acoshift/leaptips/vendor/github.com/acoshift/session.(*Manager).Middleware.func1.1.1()
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/session/middleware.go:48 +0x183
github.com/acoshift/leaptips/vendor/github.com/acoshift/session.(*sessionWriter).WriteHeader(0xc0420f4b40, 0xc8)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/session/writer.go:27 +0x48
github.com/acoshift/leaptips/vendor/github.com/acoshift/hime.(*appContext).writeHeader(0xc0421a9a00)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/hime/result.go:45 +0x5d
github.com/acoshift/leaptips/vendor/github.com/acoshift/hime.(*appContext).JSON.func1.1()
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/hime/result.go:168 +0x8f
github.com/acoshift/leaptips/vendor/github.com/acoshift/hime.(*appContext).invokeBeforeRender.func1(0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/hime/result.go:121 +0x2b
net/http.HandlerFunc.ServeHTTP(0xc04227ee60, 0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Go/src/net/http/server.go:1918 +0x4b
github.com/acoshift/leaptips/pkg/app.Handler.func1.4.1(0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/pkg/app/handler.go:148 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc0420f5220, 0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Go/src/net/http/server.go:1918 +0x4b
github.com/acoshift/leaptips/vendor/github.com/acoshift/hime.(*appContext).invokeBeforeRender(0xc0421a9a00, 0xc0424cfd10)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/hime/result.go:122 +0xd2
github.com/acoshift/leaptips/vendor/github.com/acoshift/hime.(*appContext).JSON.func1(0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/hime/result.go:166 +0xd2
github.com/acoshift/leaptips/vendor/github.com/acoshift/hime.ResultFunc.Response(0xc0420f5200, 0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/hime/hime.go:93 +0x4b
github.com/acoshift/leaptips/vendor/github.com/acoshift/hime.Wrap.func1(0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/hime/handler.go:16 +0x195
net/http.HandlerFunc.ServeHTTP(0xc0421e8020, 0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Go/src/net/http/server.go:1918 +0x4b
github.com/acoshift/leaptips/pkg/app.userIsAnonymous.func1(0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/pkg/app/middleware.go:64 +0xf9
net/http.HandlerFunc.ServeHTTP(0xc0422b3320, 0xcad180, 0xc0420f4b40, 0xc0422dd600)
	C:/Go/src/net/http/server.go:1918 +0x4b
github.com/acoshift/leaptips/vendor/github.com/acoshift/httprouter.(*Router).ServeHTTP(0xc04212d600, 0xcad180, 0xc0420f4b40, 0xc0422dd400)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/httprouter/router.go:332 +0x493
github.com/acoshift/leaptips/pkg/app.injectUserContext.func1.1(0xcad180, 0xc0420f4b40, 0xc0422dd400)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/pkg/app/middleware.go:37 +0x285
net/http.HandlerFunc.ServeHTTP(0xc0420f4700, 0xcad180, 0xc0420f4b40, 0xc0422dd400)
	C:/Go/src/net/http/server.go:1918 +0x4b
github.com/acoshift/leaptips/vendor/github.com/acoshift/session.(*Manager).Middleware.func1.1(0xcad800, 0xc0425141c0, 0xc0422dd300)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/session/middleware.go:53 +0x299
net/http.HandlerFunc.ServeHTTP(0xc0420f4860, 0xcad800, 0xc0425141c0, 0xc0422dd300)
	C:/Go/src/net/http/server.go:1918 +0x4b
github.com/acoshift/leaptips/pkg/app.cors.func1.1(0xcad800, 0xc0425141c0, 0xc0422dd300)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/pkg/app/middleware.go:104 +0x83
net/http.HandlerFunc.ServeHTTP(0xc0420f4880, 0xcad800, 0xc0425141c0, 0xc0422dd300)
	C:/Go/src/net/http/server.go:1918 +0x4b
github.com/acoshift/leaptips/vendor/github.com/acoshift/hime.(*app).ServeHTTP(0xc0423ec0a0, 0xcad800, 0xc0425141c0, 0xc0422dd200)
	C:/Users/arthur/gocode/src/github.com/acoshift/leaptips/vendor/github.com/acoshift/hime/http.go:15 +0xcc
net/http.serverHandler.ServeHTTP(0xc04223dd40, 0xcad800, 0xc0425141c0, 0xc0422dd200)
	C:/Go/src/net/http/server.go:2619 +0xbb
net/http.(*conn).serve(0xc0423ed040, 0xcadf40, 0xc0421a9880)
	C:/Go/src/net/http/server.go:1801 +0x724
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2720 +0x28f
```

It may be a stupid thing, but I cant figure out what it is and I dont want to spend too much on it.. Any ideas ?

**Comment by acoshift** [comment]
Did You forget to run redis ?

**Comment by arthurgustin** [comment]
Thats it, now it sounds obvious when I know the redis standard port (I've never used it before)
Thank you mate !
